cuda_visible_devices: 0

data_path: data/beauty.csv # path to csv with structure as in after get_movielens_data(include_time=True)
splitting: 'leave-one-out'

dataloader:
  batch_size: 4096
  n_neg_samples: 0

model: 'SASRec' # not used
model_params:
  fwd_type: 'rece' # DO NOT CHANGE
  sampling: 'no_sampling' # DO NOT USE FOR CE AND RCE
  
  maxlen: 200
  hidden_units: 256
  num_blocks: 2
  num_heads: 1
  dropout_rate: 0.5
  
  n_buckets: 907
  buckets_per_chunk: 1
  n_extra_chunks: 8
  rounds: 64

trainer_params:
  num_epochs: 300
  patience: 10    # nmb of epoches to wait for improvement in validation metrics
  skip_epochs: 1  # how often to check if validation metrics are improved
  learning_rate: 0.001
  seed: 1235
